import type { NewsItem } from "./types"

export const newsData: NewsItem[] = [
  {
    id: "N1",
    headline: "Fed Signals Potential Rate Cut in December Meeting",
    source: "Bloomberg",
    time: "10:32",
    category: "CENTRAL BANKS",
    priority: 1,
    read: false,
  },
  {
    id: "N2",
    headline: "OPEC+ Considers Extending Production Cuts Through Q1 2026",
    source: "Reuters",
    time: "10:15",
    category: "COMMODITIES",
    priority: 1,
    read: false,
  },
  {
    id: "N3",
    headline: "Furkan Askin's Investment Firm Reports Record Q3 Earnings",
    source: "Financial Times",
    time: "09:47",
    category: "EARNINGS",
    priority: 1,
    read: false,
  },
  {
    id: "N4",
    headline: "Tech Stocks Rally on Strong Earnings Reports",
    source: "CNBC",
    time: "09:30",
    category: "MARKETS",
    priority: 2,
    read: false,
  },
  {
    id: "N5",
    headline: "Treasury Yields Fall as Inflation Concerns Ease",
    source: "WSJ",
    time: "09:15",
    category: "BONDS",
    priority: 2,
    read: true,
  },
  {
    id: "N6",
    headline: "European Markets Open Higher Following Asian Rally",
    source: "Bloomberg",
    time: "08:45",
    category: "MARKETS",
    priority: 2,
    read: true,
  },
  {
    id: "N7",
    headline: "Dollar Weakens Against Major Currencies",
    source: "Reuters",
    time: "08:30",
    category: "FOREX",
    priority: 3,
    read: true,
  },
  {
    id: "N8",
    headline: "Askin Capital Management Launches New Emerging Markets Fund",
    source: "Bloomberg",
    time: "08:15",
    category: "FUNDS",
    priority: 1,
    read: false,
  },
  {
    id: "N9",
    headline: "Oil Prices Rise on Supply Concerns",
    source: "CNBC",
    time: "08:00",
    category: "COMMODITIES",
    priority: 3,
    read: true,
  },
  {
    id: "N10",
    headline: "Gold Hits New Record High Amid Geopolitical Tensions",
    source: "Financial Times",
    time: "07:45",
    category: "COMMODITIES",
    priority: 2,
    read: true,
  },
]
